In [1]:
import seaborn as sns

In [2]:
df = sns.load_dataset('iris')
df.head()

,sepal_length,sepal_width,petal_length,petal_width,species
0,5.1,3.5,1.4,0.2,setosa
1,4.9,3.0,1.4,0.2,setosa
2,4.7,3.2,1.3,0.2,setosa
3,4.6,3.1,1.5,0.2,setosa
4,5.0,3.6,1.4,0.2,setosa


In [3]:
from sklearn.preprocessing import normalize

In [4]:
df.columns

Index(['sepal_length', 'sepal_width', 'petal_length', 'petal_width',
       'species'],
      dtype='object')

In [5]:
normalize(df[['sepal_length', 'sepal_width', 'petal_length', 'petal_width']])

array([[0.80377277, 0.55160877, 0.22064351, 0.0315205 ],
       [0.82813287, 0.50702013, 0.23660939, 0.03380134],
       [0.80533308, 0.54831188, 0.2227517 , 0.03426949],
       [0.80003025, 0.53915082, 0.26087943, 0.03478392],
       [0.790965  , 0.5694948 , 0.2214702 , 0.0316386 ],
       [0.78417499, 0.5663486 , 0.2468699 , 0.05808704],
       [0.78010936, 0.57660257, 0.23742459, 0.0508767 ],
       [0.80218492, 0.54548574, 0.24065548, 0.0320874 ],
       [0.80642366, 0.5315065 , 0.25658935, 0.03665562],
       [0.81803119, 0.51752994, 0.25041771, 0.01669451],
       [0.80373519, 0.55070744, 0.22325977, 0.02976797],
       [0.786991  , 0.55745196, 0.26233033, 0.03279129],
       [0.82307218, 0.51442011, 0.24006272, 0.01714734],
       [0.8025126 , 0.55989251, 0.20529392, 0.01866308],
       [0.81120865, 0.55945424, 0.16783627, 0.02797271],
       [0.77381111, 0.59732787, 0.2036345 , 0.05430253],
       [0.79428944, 0.57365349, 0.19121783, 0.05883625],
       [0.80327412, 0.55126656,

In [6]:
import pandas as pd
df1 = pd.DataFrame(normalize(df[['sepal_length', 'sepal_width', 'petal_length', 'petal_width']]), columns=['sepal_length', 'sepal_width', 'petal_length', 'petal_width'])
df1.head()

,sepal_length,sepal_width,petal_length,petal_width
0,0.803773,0.551609,0.220644,0.031521
1,0.828133,0.507020,0.236609,0.033801
2,0.805333,0.548312,0.222752,0.034269
3,0.800030,0.539151,0.260879,0.034784
4,0.790965,0.569495,0.221470,0.031639


In [7]:
# checking the max and min values of the columns of iris dataset
df[['sepal_length', 'sepal_width', 'petal_length', 'petal_width']].max(), df[['sepal_length', 'sepal_width', 'petal_length', 'petal_width']].min()

(sepal_length    7.9
 sepal_width     4.4
 petal_length    6.9
 petal_width     2.5
 dtype: float64,
 sepal_length    4.3
 sepal_width     2.0
 petal_length    1.0
 petal_width     0.1
 dtype: float64)

In [8]:
df1[['sepal_length', 'sepal_width', 'petal_length', 'petal_width']].max(), df1[['sepal_length', 'sepal_width', 'petal_length', 'petal_width']].min()


(sepal_length    0.860939
 sepal_width     0.607125
 petal_length    0.636981
 petal_width     0.280419
 dtype: float64,
 sepal_length    0.653877
 sepal_width     0.238392
 petal_length    0.167836
 petal_width     0.014727
 dtype: float64)

In [9]:
df1.head()

,sepal_length,sepal_width,petal_length,petal_width
0,0.803773,0.551609,0.220644,0.031521
1,0.828133,0.507020,0.236609,0.033801
2,0.805333,0.548312,0.222752,0.034269
3,0.800030,0.539151,0.260879,0.034784
4,0.790965,0.569495,0.221470,0.031639


In [10]:
# checking the max and min values of normalized columns
df1.max(), df1.min()

(sepal_length    0.860939
 sepal_width     0.607125
 petal_length    0.636981
 petal_width     0.280419
 dtype: float64,
 sepal_length    0.653877
 sepal_width     0.238392
 petal_length    0.167836
 petal_width     0.014727
 dtype: float64)

In [11]:
import numpy as np
data = np.array([[1, 2, 3],
                 [4, 5, 6]])

normalized_data = normalize(data, norm='l2')
print(normalized_data)

[[0.26726124 0.53452248 0.80178373]
 [0.45584231 0.56980288 0.68376346]]


In Simple Terms

normalize() → Makes each row have length 1

MinMaxScaler() → Makes each column fit between 0 and 1

StandardScaler() → Makes each column have mean 0, std 1

| Method               | What It Does                                               | Works On          | Typical Range                  | Purpose                                                 |
| -------------------- | ---------------------------------------------------------- | ----------------- | ------------------------------ | ------------------------------------------------------- |
| **`normalize()`**    | Scales each row (sample) to unit norm                      | Each row (sample) | Depends on norm (L1, L2, etc.) | Useful for text data, distance-based models             |
| **`MinMaxScaler`**   | Scales each feature (column) to a range (default 0–1)      | Each feature      | [0, 1] (or custom)             | Useful for neural networks, feature scaling             |
| **`StandardScaler`** | Centers features around 0 and scales by standard deviation | Each feature      | ~[-3, 3]                       | Useful for models sensitive to variance (e.g. SVM, PCA) |
